import React from 'react';
import type { TemplateConfig } from '../types';
import clsx from 'clsx';

interface TemplateRendererProps {
  template: TemplateConfig;
  content: string;
  emoji?: string;
  width?: number;
  className?: string;
  id?: string;
}

export const TemplateRenderer: React.FC<TemplateRendererProps> = ({
  template,
  content,
  emoji,
  width = 800,
  className,
  id,
}) => {
  const paragraphs = content.split('\n\n');

  const emojiElement = emoji ? (
    <div className="text-6xl select-none mb-4">{emoji}</div>
  ) : null;

  return (
    <div
      id={id}
      className={clsx('relative overflow-hidden shadow-lg', className)}
      style={{
        ...template.style,
        width: `${width}px`,
        minHeight: width * 0.75, // Aspect ratio at least 4:3
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
      }}
    >
      {/* Decorative Elements based on template style could go here */}
      
      <div className="flex-1 flex flex-col relative z-10">
        {/* Emoji Positioning */}
        {template.emojiPosition === 'top-left' && <div className="absolute top-0 left-0 p-8">{emojiElement}</div>}
        {template.emojiPosition === 'top-right' && <div className="absolute top-0 right-0 p-8">{emojiElement}</div>}
        
        <div className={clsx("flex-1 px-12 py-16", {
            'pt-32': template.emojiPosition?.startsWith('top'),
            'pb-32': template.emojiPosition?.startsWith('bottom')
        })}>
          {paragraphs.map((p, idx) => (
            <p 
              key={idx} 
              className="mb-6 leading-relaxed text-lg whitespace-pre-wrap"
              style={{ fontSize: '1.25rem', lineHeight: '1.8' }}
            >
              {p}
            </p>
          ))}
        </div>

        {template.emojiPosition === 'bottom-left' && <div className="absolute bottom-0 left-0 p-8">{emojiElement}</div>}
        {template.emojiPosition === 'bottom-right' && <div className="absolute bottom-0 right-0 p-8">{emojiElement}</div>}
      </div>
      
      {/* Footer / Branding if needed */}
      <div className="absolute bottom-4 right-6 opacity-50 text-xs">
        Generated by Graphic Content
      </div>
    </div>
  );
};
